enable
CISCO
configure terminal
int s0/0/0
ip address 192.167.1.1 255.255.255.0
no shutdown
end
configure terminal
int s0/0/1
ip address 192.167.2.1 255.255.255.0
no shutdown
end
configure terminal
router rip
network 192.167.1.0
network 192.167.2.0